### ISSUE TITLE
在执行时，出现了  Provider sun.tools.attach.WindowsAttachProvider could not be instantiated 报错

### ISSUE THREAD

**Issue by BlackKD** [cangqingzhe/Log4jPatch#1]
java -jar Log4j-Agent.jar 45505
sun.misc.ServiceConfigurationError: com.sun.tools.attach.spi.AttachProvider: Provider sun.tools.attach.WindowsAttachProvider could not be instantiated
Exception in thread "main" com.sun.tools.attach.AttachNotSupportedException: no providers installed
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:190)
	at AttachAgent.main(AttachAgent.java:19)
	
不是很熟悉jvm ，求教这个是哪里的问题 看起来是jre缺了什么

java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

MacOS 10.15.6

**Comment by cangqingzhe** [comment]
你可以尝试在启动jar包时指定tools.jar的地址，tools.jar一般在jdk的/lib/下，使用下面的方式启动：
java -cp "C:\\Program Files\\Java\\jdk1.8.0_191\\lib\\tools.jar" -jar Log4j-Agent.jar
在下面的链接中也提到了这个问题的解决方法：
https://stackoverflow.com/questions/57006881/sun-tools-attach-windowsattachprovider-could-not-be-instantiated

**Comment by charlotte-xiao** [comment]
(base) xiao@charlottexiao Desktop % jps
853 
5163 RemoteMavenServer36
5389 Jps
5165 Launcher
5166 AlipayApplication


(base) xiao@charlottexiao Desktop % java -cp "/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/lib/tools.jar" -jar Log4j-Agent.jar 5166
sun.misc.ServiceConfigurationError: com.sun.tools.attach.spi.AttachProvider: Provider sun.tools.attach.WindowsAttachProvider could not be instantiated
Exception in thread "main" com.sun.tools.attach.AttachNotSupportedException: no providers installed
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:190)
	at AttachAgent.main(AttachAgent.java:19)


(base) xiao@charlottexiao Desktop % java -version
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)

好像不起作用，这个改怎么解决啊。

**Comment by BlackKD** [comment]
需要确认下你使用的tools.jar是否是你用的JAVA SDK默认带

可以参考这个：https://github.com/simonis/Log4jPatch
